run_name: 'loqi_flow_v1'
outdir: null
resume: null
ema: True
wandb_params:
  mode: 'online'  # disabled, offline, online
  group: 'conformers'
  project: 'chembl3d_megalodon_diffusion'

data:
  dataset_root: "data/chembl3d_stereo"
  processed_folder: "processed"
  batch_size: &batch_size 150
  inference_batch_size: 150
  removed_h: False
  data_loader_type: "midi"
  aug_rotations: False
  scale_coords: &scale_coords 1.0

loss:
  use_loss_clamps: True
  loss_clamp_epoch_threshold: 10
  loss_clamps:
    ts_coord: 1.0
  variables:
    - variable_name: 'x'
      loss_scale: 1.0
      aggregate: 'mean'
      continuous: True
      loss_type: 'mse'
      use_distance: null
      distance_scale: null

interpolant:
  timesteps: &timesteps 25
  time_type: &time_type "continuous"
  sample_time_method: "uniform"
  sample_time_mean: 0
  sample_time_scale: 1.0
  global_variable_name: 'x'
  min_t: &min_t 0.0
  variables:
    - variable_name: 'x'
      interpolant_type: 'continuous_flow_matching' #["continuous_diffusion", "continuous_flow_matching"]
      prediction_type: 'velocity'
      optimal_transport: 'rigid' #'scale_ot'
      prior_type: 'gaussian'
      timesteps: *timesteps
      num_classes: 3
      scheduler_type: "linear"
      scheduler_cut: False
      time_type: *time_type
      min_t: *min_t
      com_free: True
      noise_sigma: 0.0
      inference_noise_sigma: 0.
    - variable_name: 'h'
      interpolant_type: "discrete_null" #["discrete_diffusion", "discrete_flow_matching"]
      num_classes: &num_atoms 17
      prior_type: null
    - variable_name: 'edge_attr'
      interpolant_type: "discrete_null" #["discrete_diffusion", "discrete_flow_matching"]
      num_classes: 9
      prior_type: null
    - variable_name: 'charges'
      interpolant_type: "discrete_null" #["discrete_diffusion", "discrete_flow_matching"]
      concat: 'h'
      num_classes: 6
      offset: 2
      prior_type: null

dynamics:
  model_name: "megav3conf"
  model_args:
    atom_classes: 23
    edge_classes: 9
    invariant_edge_feat_dim: 64
    invariant_node_feat_dim: 256
    n_vector_features: 64
    equivariant_node_feature_dim: 3
    num_layers: 10
    num_heads: 4
    dist_size: 16
    prune_edges: False
  wrapper_args:
    timesteps: *timesteps
    time_type: *time_type

sample:
  node_distribution: "${data.dataset_root}/processed/train_n_h.pickle"
  return_step_output: True

train:
  seed: 42
  gpus: 1
  n_epochs: 800
  enable_progress_bar: True
  gradient_clip_value: 1.0
  log_freq: 50
  val_freq: 2
  checkpoint_monitor: opt_median_relative_energy
  checkpoint_monitor_mode: min
  checkpoint_every_n_train_steps: 500

evaluation:
  type: conformers
  max_molecules: 300
  timesteps: *timesteps
  compute_3D_metrics: True
  compute_energy_metrics: True
  compute_stereo_metrics: True
  scale_coords: *scale_coords
  energy_metrics_args:
    model_path: src/megalodon/metrics/aimnet2/cpcm_model/wb97m_cpcms_v2_0.jpt
    batchsize: 100
    opt_metrics: True
    opt_params:
      fmax: 2e-3
      max_nstep: 3000

optimizer:
  type: adamw
  lr: 1.e-4
  weight_decay: 1.e-12
  amsgrad: True

lr_scheduler:
  type: linear_warmup
  initial_lr: 1.e-5
  final_lr: 1.e-4
  num_warmup_steps: 1000
  interval: step
  frequency: 1 #not in config but this is the default
